apiVersion: v1
kind: Service
metadata:
  name: reply-server
  labels:
    app: reply-server
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: http
  - name: metrics
    port: 89
    targetPort: metrics
  selector:
    app: reply-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reply-server-v1
  labels:
    app: reply-server
spec:
  replicas: 10
  selector:
    matchLabels:
      app: reply-server
      version: v1.0.0
  template:
    metadata:
      labels:
        app: reply-server
        version: v1.0.0
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9101"
    spec:
      containers:
      - name: reply-server
        image: reply-server-img
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8080
        - name: probe
          containerPort: 8086
        - name: metrics
          containerPort: 9101
        env:
        - name: VERSION
          value: v1.0.0
        livenessProbe:
          httpGet:
            path: /live
            port: probe
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /ready
            port: probe
          periodSeconds: 5
